apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: ecomarket
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: AWS_ECR_URI
          # 104844728320.dkr.ecr.ap-northeast-2.amazonaws.com/delivery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: delivery-info
                  key: dbhost
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: delivery-db-pass
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-db-pass
                  key: password
