apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 104844728320.dkr.ecr.ap-northeast-2.amazonaws.com/delivery:latest
          ports:
            - containerPort: 8083
