apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: delivery
  namespace: ecomarket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delivery
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

