apiVersion: v1
kind: Service
metadata:
  name: delivery-svc
  namespace: ecomarket
  labels:
    app: delivery
spec:
  ports:
    - port: 80
      targetPort: 8083
  selector:
    app: delivery
  # type: LoadBalancer
  type: NodePort
